### ISSUE TITLE
What's the use case for this?

### ISSUE THREAD

**Issue by gdevenyi** [joshunrau/autossh#1]
I'm not sure what this is for, I don't understand what one would use it for.

**Comment by joshunrau** [comment]
The primary use case is just convenience. For instance, if I want to work on a project using data on CC on my own computer (e.g., if I want to use VS Code), I can just define private environment variables and then easily transfer the data without having to enter my username and password, and the rest of whatever rsync command I would need, every time. Of course, this might not save that much time for each use, but if it saves a minute several times per week for a year that would probably add up to the time it took me to make it!

**Comment by gdevenyi** [comment]
Interesting solution, creative.

You may be interested that this is the application of ssh keys, ssh-agent and the ~/.ssh/config file.

Have fun googling :+:1

**Comment by joshunrau** [comment]
Hahaha thank you
